/*
 * Blox Emulation - local Luau compatibility loader
 *
 * This module intentionally forces luau-web's Asyncify backend instead of its
 * automatic JSPI/Asyncify selection. Put Luau.Web.Asyncify.js beside this file.
 *
 * Pinned runtime source expected by install-local-luau.bat:
 *   luau-web 1.4.0
 *
 * This wrapper exposes the API your emulator already expects:
 *   LuauState
 *   Mutable
 *   CompileError
 *
 * NOTE:
 * This is a LOCALIZED/PINNED compatibility runtime, not a handwritten Luau
 * interpreter. The actual Luau VM is the WebAssembly VM embedded/generated by
 * the pinned backend.
 */

import createLuauCore from "./Luau.Web.Asyncify.js";

// The emulator and standalone runner share the same fixed Luau ceiling. The
// WASM heap still begins small and grows on demand; this only raises its hard
// limit and is deliberately not exposed as an in-game setting.
if (!globalThis.__bloxBootSettings) globalThis.__bloxBootSettings = {};
if (!Number.isFinite(Number(globalThis.__bloxBootSettings.mapLoaderMemoryMb))) {
    globalThis.__bloxBootSettings.mapLoaderMemoryMb = 512;
}

const Luau = {
    LUA_VALUE: Symbol("LuaValue"),
    JS_VALUE: Symbol("JsValue"),
    JS_MUTABLE: Symbol("JsMutable"),
    securityTransmitList: new Map(),
    options: new Map([["LUA_IMPLICIT_ARRAYS_TO_JS_ARRAYS", true]]),
    states: [],
};

let initialized = false;
let initializationPromise = null;

// luau-web@1.4.0 has two expensive reference-cache bugs in its generated
// JavaScript glue:
//
// 1. getPersistentRef() stores `jsValueReverse` entries as numeric refs, but
//    later tries to read JS_VALUE directly from that number.  Every access to a
//    host object/function member therefore creates another permanent ref.
// 2. tryClassicVector3ToLua() creates a fresh native Luau table every time the
//    same host Vector3 is read.  Position/Size/CFrame vector reads in gameplay
//    loops can consequently retain thousands of equivalent Lua tables.
//
// Keep these fixes here rather than hand-editing the generated WASM bundle so a
// pinned runtime refresh cannot silently overwrite them.
function installBloxInteropCacheFixes() {
    if (
        Luau.getPersistentRef?.__bloxOwnerAwareCache &&
        Luau.tryClassicVector3ToLua?.__bloxStableVectorCache
    ) {
        return;
    }

    Luau.__bloxInteropCacheFixesInstalled = true;

    const getPersistentRef = function getPersistentRef(
        stateIdx,
        jsValue,
        parent,
        key
    ) {
        const stateData = Luau.states[stateIdx];

        if (!stateData) {
            const RuntimeError = Luau.RuntimeError || Error;
            throw new RuntimeError(`no state for env id ${stateIdx}`);
        }

        if (Luau.securityTransmitList.has(jsValue)) {
            Luau.fprintwarn?.(
                "illegal state: can't get persistent ref, js value '%s' is blocked",
                key ? String(key) : "unknown"
            );
            return 0;
        }

        // Plain host objects have identity independent of the path used to
        // reach them, so one underlying object needs only one persistent ref.
        // Functions additionally need their receiver in the cache key so a
        // shared method implementation keeps the correct `this` binding.
        const callable = typeof jsValue === "function";
        const parentKey = callable
            ? (parent ?? null)
            : null;
        let refsByParent = stateData.jsValueRefsByParent.get(jsValue);

        if (refsByParent) {
            const existingRef = refsByParent.get(parentKey);
            const existing = stateData.jsValueCache.get(existingRef);
            const existingData = existing?.[Luau.JS_VALUE];

            if (existingData && !existingData.released) {
                // Keep the legacy reverse lookup useful to the rest of the
                // generated bridge (it represents the most recently used ref).
                stateData.jsValueReverse.set(jsValue, existingRef);
                return existingRef;
            }

            if (existingRef !== undefined) refsByParent.delete(parentKey);
        } else {
            refsByParent = new Map();
            stateData.jsValueRefsByParent.set(jsValue, refsByParent);
        }

        const ref = stateData.nextJSRef--;
        const effectiveParent = callable
            ? parent
            : null;
        const parentRef = stateData.jsValueReverse.get(effectiveParent);
        const parentWrapper = stateData.jsValueCache.get(parentRef);

        const obj = {
            [Luau.JS_VALUE]: {
                ref,
                value: jsValue,
                parent: parentWrapper || effectiveParent,
                key,
                released: false,
                release() {
                    if (this.released) return;

                    stateData.jsValueCache.delete(ref);

                    if (stateData.jsValueReverse.get(jsValue) === ref) {
                        stateData.jsValueReverse.delete(jsValue);
                    }

                    if (refsByParent.get(parentKey) === ref) {
                        refsByParent.delete(parentKey);
                    }

                    if (refsByParent.size === 0) {
                        stateData.jsValueRefsByParent.delete(jsValue);
                    }

                    this.released = true;
                },
            },

            toString() {
                return `[JsReference ${String(typeof jsValue)} ${String(ref)}]`;
            },
        };

        stateData.jsValueCache.set(ref, obj);
        stateData.jsValueReverse.set(jsValue, ref);
        refsByParent.set(parentKey, ref);
        return ref;
    };

    getPersistentRef.__bloxOwnerAwareCache = true;
    Luau.getPersistentRef = getPersistentRef;

    const tryClassicVector3ToLua = function tryClassicVector3ToLua(
        stateIdx,
        value
    ) {
        try {
            if (!value || typeof value !== "object") return null;

            const get = key =>
                value instanceof Map
                    ? value.get(key)
                    : value[key];

            if (get("__bloxVector3Bridge") !== true) return null;

            const stateData = Luau.states[stateIdx];
            const metatable = stateData?.classicVector3Metatable;

            if (
                !stateData ||
                !metatable ||
                !Luau.safeIn(Luau.LUA_VALUE, metatable)
            ) {
                return null;
            }

            const metatableData = metatable[Luau.LUA_VALUE];

            if (metatableData.released || metatableData.type !== "ltable") {
                return null;
            }

            const x = Number(get("X")) || 0;
            const y = Number(get("Y")) || 0;
            const z = Number(get("Z")) || 0;
            const cached = stateData.classicVector3BridgeCache.get(value);
            const cachedData = cached?.table?.[Luau.LUA_VALUE];

            if (
                cached &&
                cached.x === x &&
                cached.y === y &&
                cached.z === z &&
                cached.metatableRef === metatableData.ref &&
                cachedData &&
                !cachedData.released
            ) {
                return [cachedData.type, String(cachedData.ref)];
            }

            // Position/Velocity objects in the emulator are intentionally
            // updated in place.  Once their components change, the registry
            // handle for the previous immutable snapshot is no longer needed
            // by the JS bridge.  Unref that external handle before replacing
            // it; any Luau local/global that already received the table keeps
            // its own normal VM reference and remains valid.
            if (cachedData && !cachedData.released) {
                try {
                    cachedData.release();
                } finally {
                    stateData.luaValueCache.delete(cachedData.ref);
                }
            }

            const state = metatableData.state;
            const ref = Luau._createLuaTable(state);
            const table = Luau.LuaValue(
                state,
                stateIdx,
                "ltable",
                ref
            );

            Luau.newIndexLuaTable(stateIdx, table, "X", x, true);
            Luau.newIndexLuaTable(stateIdx, table, "Y", y, true);
            Luau.newIndexLuaTable(stateIdx, table, "Z", z, true);
            Luau.newIndexLuaTable(
                stateIdx,
                table,
                "__bloxNativeVector3",
                true,
                true
            );
            Luau._setrawmetatable(state, ref, metatableData.ref);

            // Roblox Vector3 values are immutable. Besides matching that API,
            // readonly snapshots make it safe to return the cached table again
            // without one caller changing what a later property read observes.
            stateData.env?.setreadonly?.(table, true);

            stateData.classicVector3BridgeCache.set(value, {
                x,
                y,
                z,
                metatableRef: metatableData.ref,
                table,
            });

            return ["ltable", String(ref)];
        } catch (error) {
            Luau.fprintwarn?.(
                "classic Vector3 bridge conversion failed",
                error
            );
            return null;
        }
    };

    tryClassicVector3ToLua.__bloxStableVectorCache = true;
    Luau.tryClassicVector3ToLua = tryClassicVector3ToLua;
}

async function ensureInitialized() {
    if (initialized) return true;
    if (initializationPromise) return initializationPromise;

    initializationPromise = (async () => {
        const moduleInstance = await createLuauCore(Luau);
        Object.assign(Luau, moduleInstance);
        installBloxInteropCacheFixes();
        initialized = true;
        return true;
    })();

    try {
        return await initializationPromise;
    } catch (error) {
        initializationPromise = null;
        throw error;
    }
}

class CompileError extends Error {
    constructor(message) {
        super(String(message));
        this.name = "CompileError";
    }
}

// Classic Roblox's Lua object bridge was permissive about member casing.
// A large amount of 2007-2010 content uses forms such as BodyPosition.position,
// BodyForce.force, CFrame.lookVector, BrickColor.Random(), and object.className.
// Keep exact keys authoritative, but resolve an existing string key
// case-insensitively before creating a new property.
const mutableCaseKeyCache = new WeakMap();
const mutableMutationHooks = new WeakMap();
const mutableProxyTargets = new WeakMap();

function notifyMutableMutation(target, key, value, previousValue) {
    if (Object.is(value, previousValue)) return;

    const hook = mutableMutationHooks.get(target);
    if (typeof hook !== "function") return;

    try {
        hook(key, value, previousValue);
    } catch (error) {
        // A host-side index/event observer must never make an otherwise valid
        // Luau property assignment fail inside the WASM bridge.
        console.error("[Luau Mutable mutation hook]", error);
    }
}

// Register a host observer for writes made through either ordinary JavaScript
// property assignment or luau-web's Map.set() interop path.  The latter is
// important: it lets the emulator keep Parent/Name indexes synchronous without
// polling every Instance or modifying the generated WASM glue.
function setMutableMutationHook(mutable, hook) {
    const target = mutableProxyTargets.get(mutable) ||
        (mutable instanceof Map ? mutable : null);

    if (!target) return false;

    if (typeof hook === "function")
        mutableMutationHooks.set(target, hook);
    else
        mutableMutationHooks.delete(target);

    return true;
}

// Engine-owned mirrors (physics transforms, measured velocities) need to
// update host values without pretending Lua authored another property write.
// This also bypasses Proxy key resolution in large tight synchronization loops.
function setMutableValueSilently(mutable, key, value) {
    const target = mutableProxyTargets.get(mutable) ||
        (mutable instanceof Map ? mutable : null);
    if (!target) return false;
    const actual = resolveMutableKey(target, key);
    target.set(actual, value);
    rememberMutableKey(target, actual);
    return true;
}

function getMutableCaseKeyCache(target) {
    let cache = mutableCaseKeyCache.get(target);
    if (cache) return cache;

    cache = new Map();
    for (const key of target.keys()) {
        if (typeof key === "string") {
            const lower = key.toLowerCase();
            if (!cache.has(lower)) cache.set(lower, key);
        }
    }
    mutableCaseKeyCache.set(target, cache);
    return cache;
}

function resolveMutableKey(target, prop) {
    if (target.has(prop) || typeof prop !== "string") return prop;
    return getMutableCaseKeyCache(target).get(prop.toLowerCase()) ?? prop;
}

function rememberMutableKey(target, prop) {
    if (typeof prop !== "string") return;
    const cache = getMutableCaseKeyCache(target);
    const lower = prop.toLowerCase();
    if (!cache.has(lower)) cache.set(lower, prop);
}

function Mutable(object = {}) {
    const map = object instanceof Map
        ? object
        : new Map(Object.entries(object));

    map.set(Luau.JS_MUTABLE, true);

    const proxy = new Proxy(map, {
        get(target, prop, receiver) {
            const resolved = resolveMutableKey(target, prop);
            if (target.has(resolved))
                return target.get(resolved);

            // Map accessors (notably `size`) require the real Map as receiver.
            // Reflecting them through the Proxy throws "incompatible receiver"
            // in current Chromium. Wrap mutators as well so the legacy
            // case-insensitive key cache stays correct when host code uses the
            // Map API instead of property assignment.
            if (prop === "set") {
                return (key, value) => {
                    const actual = resolveMutableKey(target, key);
                    const previousValue = target.get(actual);
                    target.set(actual, value);
                    rememberMutableKey(target, actual);
                    notifyMutableMutation(target, actual, value, previousValue);
                    return receiver;
                };
            }

            if (prop === "delete") {
                return key => {
                    const actual = resolveMutableKey(target, key);
                    const previousValue = target.get(actual);
                    const removed = target.delete(actual);
                    if (removed) mutableCaseKeyCache.delete(target);
                    if (removed) notifyMutableMutation(
                        target,
                        actual,
                        undefined,
                        previousValue
                    );
                    return removed;
                };
            }

            if (prop === "clear") {
                return () => {
                    const previousEntries = mutableMutationHooks.has(target)
                        ? Array.from(target.entries())
                        : null;
                    target.clear();
                    mutableCaseKeyCache.delete(target);
                    if (previousEntries) {
                        for (const [key, previousValue] of previousEntries) {
                            notifyMutableMutation(
                                target,
                                key,
                                undefined,
                                previousValue
                            );
                        }
                    }
                };
            }

            const nativeValue = Reflect.get(target, prop, target);

            if (typeof nativeValue === "function")
                return nativeValue.bind(target);

            return nativeValue;
        },

        set(target, prop, value) {
            const resolved = resolveMutableKey(target, prop);
            const previousValue = target.get(resolved);
            target.set(resolved, value);
            rememberMutableKey(target, resolved);
            notifyMutableMutation(target, resolved, value, previousValue);
            return true;
        },

        has(target, prop) {
            const resolved = resolveMutableKey(target, prop);
            return target.has(resolved) || Reflect.has(target, prop);
        },

        getPrototypeOf() {
            return Map.prototype;
        },
    });

    mutableProxyTargets.set(proxy, map);
    return proxy;
}

class LuauState {
    static async createAsync(initialEnv = undefined) {
        await ensureInitialized();
        // Some Emscripten builds finish installing their interop functions as
        // the runtime becomes ready. Reassert the shims immediately before a
        // state is allocated so that late initialization cannot replace them.
        installBloxInteropCacheFixes();

        const instance = new LuauState();

        instance.state = await Luau._makeLuaState(instance.stateIdx);
        // _makeLuaState invokes luau-web's ensureInterop(), which reinstalls the
        // package defaults. Apply the corrected functions after that final
        // initialization point and before any host globals are transmitted.
        installBloxInteropCacheFixes();
        instance.env = Luau.states[instance.stateIdx].env;

        if (initialEnv) {
            for (const [key, value] of Object.entries(initialEnv)) {
                const ok = instance.env.set(key, value, true);

                if (!ok) {
                    const message =
                        `illegal state: Lua global "${key}" could not be installed`;

                    if (typeof Luau.fprintwarn === "function")
                        Luau.fprintwarn(message);
                    else
                        console.warn("[Luau]", message);
                }
            }
        }

        return instance;
    }

    constructor() {
        if (!initialized) {
            throw new Error(
                "Luau is not initialized. Use await LuauState.createAsync(...)"
            );
        }

        this.stateIdx = Luau.states.length + 1;

        Luau.states[this.stateIdx] = {
            luaValueCache: new Map(),
            jsValueCache: new Map(),
            jsValueReverse: new Map(),
            jsValueRefsByParent: new Map(),
            classicVector3BridgeCache: new WeakMap(),
            transactionData: [],
            nextJSRef: -1,
            nextTXKey: 0,
        };

        this.destroyed = false;
        this.state = null;
        this.env = null;
    }

    setClassicVector3Metatable(metatable) {
        this._assertAlive();
        Luau.states[this.stateIdx].classicVector3Metatable = metatable || null;
    }

    createTable(initial = {}, metatable = null) {
        this._assertAlive();

        const ref = Luau._createLuaTable(this.state);
        if (ref === false || ref === null || ref === undefined) {
            const GlueError = Luau.GlueError || Error;
            throw new GlueError(
                "Luau VM could not allocate a native table during this host call"
            );
        }
        const table = Luau.LuaValue(
            this.state,
            this.stateIdx,
            "ltable",
            ref
        );

        const entries = initial instanceof Map
            ? Array.from(initial.entries())
            : Object.entries(initial);

        for (const [key, value] of entries) {
            table.set(key, value, true);
        }

        if (metatable) {
            this.env.setrawmetatable(table, metatable);
        }

        return table;
    }

    // Create a REAL Luau array table rather than a JavaScript host object.
    // This is required for classic Roblox collection APIs: Lua's # operator,
    // ipairs(), and numeric indexing only have native table semantics when the
    // value actually lives in the Luau VM.
    createArray(items = [], extra = null) {
        this._assertAlive();

        const values = Array.from(items || []);
        const entries = new Map();

        for (let i = 0; i < values.length; i++) {
            entries.set(i + 1, values[i]);
        }

        const table = this.createTable(entries);

        if (extra instanceof Map || (extra && typeof extra === "object")) {
            const extraEntries = extra instanceof Map
                ? extra
                : new Map(Object.entries(extra));

            if (extraEntries.size > 0) {
                // Roblox collection results are ordinary numeric arrays.
                // Compatibility conveniences such as Count/Get must remain
                // indexable without appearing in pairs(), which only visits
                // raw table entries. Put those conveniences behind __index.
                const extraTable = this.createTable(extraEntries);
                const metatable = this.createTable({ __index: extraTable });
                this.env.setrawmetatable(table, metatable);
            }
        }

        return table;
    }

    _assertAlive() {
        if (this.destroyed) {
            const GlueError = Luau.GlueError || Error;
            throw new GlueError("Cannot use destroyed Luau state");
        }
    }

    getValue(index) {
        this._assertAlive();

        const transactionId = Luau._getLuaValue(this.state, index);
        const transactionData = Luau.states[this.stateIdx].transactionData;
        const raw = transactionData[transactionId];

        let descriptor = raw;

        if (typeof raw === "string") {
            try {
                descriptor = JSON.parse(raw);
            } catch {
                descriptor = raw;
            }
        }

        try {
            return Luau.luauToJsValue(
                this.stateIdx,
                this.state,
                descriptor
            );
        } finally {
            // sendValueToJS() leaves the descriptor in the transaction table.
            // A map containing thousands of scripts calls loadstring() many
            // times, so retaining every descriptor for the lifetime of the VM
            // caused avoidable memory growth.
            delete transactionData[transactionId];
        }
    }

    makeTransaction(value) {
        this._assertAlive();

        const stateData = Luau.states[this.stateIdx];
        const id = stateData.nextTXKey++;

        stateData.transactionData[id] = value;
        return id;
    }

    getStats() {
        this._assertAlive();
        const stateData = Luau.states[this.stateIdx];
        let memory = null;
        try {
            memory = typeof Luau.__bloxMemoryInfo === "function"
                ? Luau.__bloxMemoryInfo()
                : null;
        } catch {}

        return {
            stateIdx: this.stateIdx,
            luaValueRefs: stateData?.luaValueCache?.size || 0,
            jsValueRefs: stateData?.jsValueCache?.size || 0,
            pendingTransactions: stateData?.transactionData
                ? Object.keys(stateData.transactionData).length
                : 0,
            memory
        };
    }

    loadstring(
        source,
        chunkname = "LuauWeb",
        throwOnCompilationError = false
    ) {
        this._assertAlive();

        const status = Luau._luauLoad(
            this.state,
            this.makeTransaction(String(source)),
            this.makeTransaction(String(chunkname))
        );

        if (status !== 0) {
            const error = this.getValue(-1);

            if (throwOnCompilationError)
                throw new CompileError(error);

            return error;
        }

        return this.getValue(-1);
    }

    destroy() {
        this._assertAlive();

        this.destroyed = true;
        this.env = null;

        Luau.states[this.stateIdx] = null;

        if (this.state != null)
            Luau._luauClose(this.state);

        this.state = null;
    }
}


// luau-web maps a returned JavaScript Array to multiple Luau return values.
// Keep the emulator's existing helper name so APIs like FindPartOnRay can
// return legacy tuples while using the real WebAssembly Luau VM.
function LuaMultiReturn(...values) {
    if (values.length === 1 && Array.isArray(values[0]))
        return values[0];
    return values;
}

// Small diagnostics hook useful while testing the emulator.
function getLuauRuntimeInfo() {
    let memory = null;
    try {
        memory = typeof Luau.__bloxMemoryInfo === "function"
            ? Luau.__bloxMemoryInfo()
            : null;
    } catch {}

    return {
        initialized,
        backend: "Asyncify",
        pinnedPackage: "luau-web@1.4.0",
        statesAllocated: Luau.states.length,
        activeStates: Luau.states.filter(Boolean).length,
        jspiForcedOff: true,
        memory
    };
}

export {
    Mutable,
    setMutableMutationHook,
    setMutableValueSilently,
    LuaMultiReturn,
    LuauState,
    CompileError,
    Luau as InternalLuauWasmModule,
    getLuauRuntimeInfo,
};
