/*
 * Blox Emulation - local Luau compatibility loader
 *
 * This module intentionally forces luau-web's Asyncify backend instead of its
 * automatic JSPI/Asyncify selection. Put Luau.Web.Asyncify.js beside this file.
 *
 * Pinned runtime source expected by install-local-luau.bat:
 *   luau-web 1.4.0
 *
 * This wrapper exposes the API your emulator already expects:
 *   LuauState
 *   Mutable
 *   CompileError
 *
 * NOTE:
 * This is a LOCALIZED/PINNED compatibility runtime, not a handwritten Luau
 * interpreter. The actual Luau VM is the WebAssembly VM embedded/generated by
 * the pinned backend.
 */

import createLuauCore from "./Luau.Web.Asyncify.js";

const Luau = {
    LUA_VALUE: Symbol("LuaValue"),
    JS_VALUE: Symbol("JsValue"),
    JS_MUTABLE: Symbol("JsMutable"),
    securityTransmitList: new Map(),
    options: new Map([["LUA_IMPLICIT_ARRAYS_TO_JS_ARRAYS", true]]),
    states: [],
};

let initialized = false;
let initializationPromise = null;

async function ensureInitialized() {
    if (initialized) return true;
    if (initializationPromise) return initializationPromise;

    initializationPromise = (async () => {
        const moduleInstance = await createLuauCore(Luau);
        Object.assign(Luau, moduleInstance);
        initialized = true;
        return true;
    })();

    try {
        return await initializationPromise;
    } catch (error) {
        initializationPromise = null;
        throw error;
    }
}

class CompileError extends Error {
    constructor(message) {
        super(String(message));
        this.name = "CompileError";
    }
}

function Mutable(object = {}) {
    const map = object instanceof Map
        ? object
        : new Map(Object.entries(object));

    map.set(Luau.JS_MUTABLE, true);

    return new Proxy(map, {
        get(target, prop, receiver) {
            const nativeValue = Reflect.get(target, prop, receiver);

            if (typeof nativeValue === "function")
                return nativeValue.bind(target);

            if (target.has(prop))
                return target.get(prop);

            return nativeValue;
        },

        set(target, prop, value) {
            target.set(prop, value);
            return true;
        },

        has(target, prop) {
            return target.has(prop) || Reflect.has(target, prop);
        },

        getPrototypeOf() {
            return Map.prototype;
        },
    });
}

class LuauState {
    static async createAsync(initialEnv = undefined) {
        await ensureInitialized();

        const instance = new LuauState();

        instance.state = await Luau._makeLuaState(instance.stateIdx);
        instance.env = Luau.states[instance.stateIdx].env;

        if (initialEnv) {
            for (const [key, value] of Object.entries(initialEnv)) {
                const ok = instance.env.set(key, value, true);

                if (!ok) {
                    const message =
                        `illegal state: Lua global "${key}" could not be installed`;

                    if (typeof Luau.fprintwarn === "function")
                        Luau.fprintwarn(message);
                    else
                        console.warn("[Luau]", message);
                }
            }
        }

        return instance;
    }

    constructor() {
        if (!initialized) {
            throw new Error(
                "Luau is not initialized. Use await LuauState.createAsync(...)"
            );
        }

        this.stateIdx = Luau.states.length + 1;

        Luau.states[this.stateIdx] = {
            luaValueCache: new Map(),
            jsValueCache: new Map(),
            jsValueReverse: new Map(),
            transactionData: [],
            nextJSRef: -1,
            nextTXKey: 0,
        };

        this.destroyed = false;
        this.state = null;
        this.env = null;
    }

    _assertAlive() {
        if (this.destroyed) {
            const GlueError = Luau.GlueError || Error;
            throw new GlueError("Cannot use destroyed Luau state");
        }
    }

    getValue(index) {
        this._assertAlive();

        const transactionId = Luau._getLuaValue(this.state, index);
        const raw = Luau.states[this.stateIdx].transactionData[transactionId];

        let descriptor = raw;

        if (typeof raw === "string") {
            try {
                descriptor = JSON.parse(raw);
            } catch {
                descriptor = raw;
            }
        }

        return Luau.luauToJsValue(
            this.stateIdx,
            this.state,
            descriptor
        );
    }

    makeTransaction(value) {
        this._assertAlive();

        const stateData = Luau.states[this.stateIdx];
        const id = stateData.nextTXKey++;

        stateData.transactionData[id] = value;
        return id;
    }

    loadstring(
        source,
        chunkname = "LuauWeb",
        throwOnCompilationError = false
    ) {
        this._assertAlive();

        const status = Luau._luauLoad(
            this.state,
            this.makeTransaction(String(source)),
            this.makeTransaction(String(chunkname))
        );

        if (status !== 0) {
            const error = this.getValue(-1);

            if (throwOnCompilationError)
                throw new CompileError(error);

            return error;
        }

        return this.getValue(-1);
    }

    destroy() {
        this._assertAlive();

        this.destroyed = true;
        this.env = null;

        Luau.states[this.stateIdx] = null;

        if (this.state != null)
            Luau._luauClose(this.state);

        this.state = null;
    }
}

// Small diagnostics hook useful while testing the emulator.
function getLuauRuntimeInfo() {
    return {
        initialized,
        backend: "Asyncify",
        pinnedPackage: "luau-web@1.4.0",
        statesAllocated: Luau.states.length,
        activeStates: Luau.states.filter(Boolean).length,
        jspiForcedOff: true,
    };
}

export {
    Mutable,
    LuauState,
    CompileError,
    Luau as InternalLuauWasmModule,
    getLuauRuntimeInfo,
};
